case insensitive grpc headers/metadata
eclipse-vertx/vertx-grpc pull request #120
Opened 2024-12-19 18:44 UTC by hcura

When using grpc web (with HTTP 1.1), the http headers are not lower cased when converting into grpc metadata. This means that they become inaccessible inside metadata since all the keys are converted to lower case on creation.

This erratic behaviour was observed in a couple of browsers that did not respect a lower case `authorization` header and transmitted upper case over the wire (confirmed on Wireshark).

This works fine for http2 since it's supposed to provide stronger case insensitive guarantees.

The test I added fails, if the `.toLowerCase()` is removed.

2025-01-02 14:44 UTC, tsegismont requested changes
Thank you for trying out Vert.x gRPC Web support and reporting this @hcura 

I have only one concern but overall it looks good to me.

2025-01-02 14:44 UTC, tsegismont commented on vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java
> +      String key = entry.getKey().toLowerCase();
`toLowerCase()` is locale sensitive, this should be:

```java
      String key = entry.getKey().toLowerCase(Locale.ROOT);
```

2025-01-03 10:49 UTC, hcura commented on vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java
> +      String key = entry.getKey().toLowerCase();
makes sense. fixed!

2025-01-03 14:17 UTC, tsegismont approved these changes
LGTM, thank you!

2025-01-03 14:24 UTC, merged